# Generated by Django 5.1.6 on 2025-03-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_payment_status_payment_creation_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Pending Approval", "Pending Approval"),
                    ("Pending Payment", "Pending Payment"),
                    ("In Progress", "In Progress"),
                ],
                default="Pending Approval",
                max_length=20,
            ),
        ),
    ]
