# Generated by Django 5.1.6 on 2025-03-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_freelancer_portfolio'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clientInterests',
            new_name='ClientInterest',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='default-service.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=250),
        ),
    ]
