# Generated by Django 5.1.6 on 2025-03-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_service_client"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Interest",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="interest",
            new_name="category",
        ),
        migrations.DeleteModel(
            name="ClientInterest",
        ),
    ]
